# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71bdde10be96e2af902b29fa01da096311a7f667f25c37a33b92fcc0ee1bfc5813db44d202ca3e11bb12e6d130dd3a4132f37eaa488d9c908fab439209554c9f

test:
  secret_key_base: e926396ac37833aa518ea51a63d7c6a02f44c0694d9e1d0d1a6b65bc4577e0115055f78a73615d4cfe12204d88ed485c4a537b5217f62cc1ed3b55ece32ecc5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
